# Generated by Django 5.2.11 on 2026-02-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('alt', models.FloatField(blank=True, null=True)),
                ('gps_fix', models.PositiveSmallIntegerField(default=3)),
                ('rat', models.CharField(max_length=10)),
                ('mccmnc', models.CharField(max_length=10)),
                ('cell_id', models.BigIntegerField(blank=True, null=True)),
                ('pci', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('band', models.CharField(max_length=30)),
                ('earfcn', models.PositiveIntegerField(blank=True, null=True)),
                ('rsrp_dbm', models.IntegerField(blank=True, null=True)),
                ('rsrq_db', models.FloatField(blank=True, null=True)),
                ('sinr_db', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['time'], name='gsm_coverag_time_9d7a60_idx'), models.Index(fields=['cell_id'], name='gsm_coverag_cell_id_50dfa4_idx'), models.Index(fields=['mccmnc'], name='gsm_coverag_mccmnc_b4cfb6_idx'), models.Index(fields=['rat'], name='gsm_coverag_rat_ef3225_idx')],
            },
        ),
        migrations.CreateModel(
            name='GSMScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='gsm_coverage/csv/')),
                ('cvs_line', models.ManyToManyField(to='gsm_coverage.csvline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
