# Generated by Django 5.2.11 on 2026-02-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gsm_coverage', '0002_gsmdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gsmdata',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='gsmdata',
            index=models.Index(fields=['operator'], name='gsm_coverag_operato_bab014_idx'),
        ),
    ]
