# Generated by Django 5.2.11 on 2026-02-11 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gsm_coverage', '0003_alter_gsmdata_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gsmdata',
            old_name='gsm_data',
            new_name='gsm_scan',
        ),
        migrations.AlterField(
            model_name='gsmdata',
            name='operator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
