# Generated by Django 5.2.11 on 2026-02-11 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsm_coverage', '0004_rename_gsm_data_gsmdata_gsm_scan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gsmscan',
            old_name='cvs_line',
            new_name='csv_lines',
        ),
    ]
