# Generated by Django 5.2.11 on 2026-02-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auths', '0002_user_id_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('group', 'name')},
        ),
    ]
