# Generated by Django 5.2.11 on 2026-02-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
