# Generated by Django 5.2.11 on 2026-02-11 21:51

import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='groups', chained_model_field='group', to='auths.role'),
        ),
    ]
